### Data Preprocessing

In [1]:
import pandas as pd
import warnings
import contractions
import json
import datetime

from textblob import TextBlob
from nltk.tokenize import word_tokenize
from nltk import pos_tag
from nltk.corpus import stopwords
from nltk.corpus import wordnet as wn
from nltk.stem import WordNetLemmatizer
from collections import defaultdict

warnings.filterwarnings(action="ignore")

---

#### I. Import CSV files

In [2]:
def import_csv_as(path):
    reviews = pd.read_csv(path)
    reviews['title_review'] = reviews['title'] + ' ' + reviews['review']
    reviews = reviews.drop(['userName','title','review','isEdited','app_id','developerResponse','app_name'],axis=1)
    return reviews

In [3]:
def import_csv_ps(path):
    reviews = pd.read_csv(path)
    reviews['title_review'] = reviews['content'].astype(str)
    reviews['date'] = reviews['at']
    reviews['rating'] = reviews['score']
    reviews = reviews[['date','rating','title_review']]
    return reviews

In [4]:
gcash_reviews_as = import_csv_as('../../Data/Raw/App Store/GCash/gcash_0613-1427.csv')
paymaya_reviews_as = import_csv_as('../../Data/Raw/App Store/PayMaya/paymaya_0613-1402.csv')

In [5]:
gcash_reviews_ps = import_csv_ps('../../Data/Raw/Play Store/gcash_reviews_playstore.csv')
paymaya_reviews_ps = import_csv_ps('../../Data/Raw/Play Store/paymaya_reviews_playstore.csv')

In [6]:
gcash_reviews_as

,date,rating,title_review
0,2018-12-29 15:24:59,3,It is starting to become pretty annoying Almos...
1,2020-05-16 07:33:32,5,Actually ok. This app gets so many negative re...
2,2020-02-04 00:25:57,3,Cash In Concern A little bit disappointed when...
3,2019-12-10 09:43:52,1,Frustrating and slow and you’re a bunch of thi...
4,2018-06-26 18:43:31,1,Payments don’t post. My payment via gcash did ...
...,...,...,...
4862,2016-01-16 11:52:50,1,FIX THIS!!! This is one of the crucial apps fo...
4863,2015-11-09 08:20:37,1,Can't access because they can't process my tra...
4864,2015-09-19 14:58:01,1,Waste of time downloading Compatibility says c...
4865,2015-09-09 11:45:00,1,Cant log in Useless app.cant access my gcash w...
4866,2015-02-06 16:10:18,2,2887 text Why does it always ask me to send a ...

In [7]:
paymaya_reviews_as

,date,rating,title_review
0,2020-03-30 01:10:54,5,VERY BAD SERVICE I have been contacting them a...
1,2020-08-06 03:55:14,1,Very poor customer service There should be a z...
2,2020-05-02 01:58:12,1,App is great but service is not I really loved...
3,2020-04-09 01:32:02,1,Make your app trustworthy really Comeon this i...
4,2020-12-01 07:59:56,1,The new update... Ok so lets be honest I love ...
...,...,...,...
2564,2016-11-15 05:07:55,1,Verification code - time waster Your verificat...
2565,2015-11-29 18:38:50,4,"Nice One Very nice idea, we can buy now online..."
2566,2016-04-09 15:51:13,2,UPDATE PLEASE! Error occured when i'm trying t...
2567,2016-03-16 10:26:02,1,Am I doing something wrong I can't receive the...
2568,2015-11-07 08:17:18,1,Can't Open App is not working after the latest...

In [8]:
gcash_reviews_ps

,date,rating,title_review
0,2021-06-02 18:32:37,1,Good for mobile online deals.
1,2021-06-02 18:32:14,1,Ilang beses nang naulit na nag load ako nag ba...
2,2021-06-02 18:32:07,4,Its a great experience and convenient
3,2021-06-02 18:31:31,5,Ok na ok sya para sa mga easy transaction lalo...
4,2021-06-02 18:31:25,5,very helpful and contented
...,...,...,...
176511,2019-04-03 09:46:14,5,I love it
176512,2019-04-03 09:38:52,4,I love the save money and invest feature of th...
176513,2019-04-03 09:38:16,1,Amex does not work and support is basically br...
176514,2019-04-03 09:33:42,5,satisfied
176515,2019-04-03,1,why u keep in pop up in my phone i font like t...

In [9]:
paymaya_reviews_ps

,date,rating,title_review
0,2021-06-15T10:22:11.000Z,5,I rated 1 star yesterday and if there's lower ...
1,2021-06-15T10:08:54.000Z,2,I cant do anything with my money! It always sa...
2,2021-06-15T10:08:14.000Z,5,Masyado na kaming maraming papel dito sa bahay...
3,2021-06-15T10:04:31.000Z,4,upgrading account and changing no is disappoin...
4,2021-06-15T09:56:32.000Z,5,I'm super stressed with my past e-wallet app s...
...,...,...,...
104558,2021-06-12T06:18:19.000Z,5,Very good in service easy to send get cash
104559,2021-06-12T06:08:23.000Z,4,Bakit walang alloutsurf sa load.
104560,2021-06-12T04:54:57.000Z,1,Keep contacting the support about the duplicat...
104561,2021-06-12T04:03:56.000Z,5,I like this apps promise
104562,2021-06-12T02:55:36.000Z,5,Nice

#### II. Preprocessing

Reference: 
1. https://stackoverflow.com/questions/45605946/how-to-do-text-pre-processing-using-spacy
2. https://towardsdatascience.com/setting-up-text-preprocessing-pipeline-using-scikit-learn-and-spacy-e09b9b76758f
3. https://medium.com/@bedigunjit/simple-guide-to-text-classification-nlp-using-svm-and-naive-bayes-with-python-421db3a72d34

---

##### A. Dropping blank rows, changing to lower case, expanding contractions, spell correction, and tokenization

In [10]:
def preprocess_a(corpus, column):
    new_column = f"{column}_tokenized"
    corpus[column].dropna(inplace=True) # Drop blank rows
    corpus[column] = [entry.lower() for entry in corpus[column]] # Lowercase text
    corpus[column] = corpus[column].apply(lambda x: contractions.fix(x)) # Expand contractions
    corpus[column] = corpus[column].apply(lambda x: str(TextBlob(x))) # Correct spelling
    corpus[column] = corpus[column].str.replace('[^\w\s]','') # Remove punctuation
    corpus[new_column] = [word_tokenize(entry) for entry in corpus[column]] # Tokenization

In [11]:
preprocess_a(gcash_reviews_as, 'title_review')
preprocess_a(paymaya_reviews_as, 'title_review')

In [12]:
preprocess_a(gcash_reviews_ps, 'title_review')
preprocess_a(paymaya_reviews_ps, 'title_review')

In [13]:
gcash_reviews_as

,date,rating,title_review,title_review_tokenized
0,2018-12-29 15:24:59,3,it is starting to become pretty annoying almos...,"[it, is, starting, to, become, pretty, annoyin..."
1,2020-05-16 07:33:32,5,actually ok this app gets so many negative rev...,"[actually, ok, this, app, gets, so, many, nega..."
2,2020-02-04 00:25:57,3,cash in concern a little bit disappointed when...,"[cash, in, concern, a, little, bit, disappoint..."
3,2019-12-10 09:43:52,1,frustrating and slow and you are a bunch of th...,"[frustrating, and, slow, and, you, are, a, bun..."
4,2018-06-26 18:43:31,1,payments do not post my payment via gcash did ...,"[payments, do, not, post, my, payment, via, gc..."
...,...,...,...,...
4862,2016-01-16 11:52:50,1,fix this this is one of the crucial apps for g...,"[fix, this, this, is, one, of, the, crucial, a..."
4863,2015-11-09 08:20:37,1,can not access because they can not process my...,"[can, not, access, because, they, can, not, pr..."
4864,2015-09-19 14:58:01,1,waste of time downloading compatibility says c...,"[waste, of, time, downloading, compatibility, ..."
4865,2015-09-09 11:45:00,1,can not log in useless appcan not access my gc...,"[can, not, log, in, useless, appcan, not, acce..."
4866,2015-02-06 16:10:18,2,2887 text why does it always ask me to send a ...,"[2887, text, why, does, it, always, ask, me, t..."

In [14]:
paymaya_reviews_as

,date,rating,title_review,title_review_tokenized
0,2020-03-30 01:10:54,5,very bad service i have been contacting them a...,"[very, bad, service, i, have, been, contacting..."
1,2020-08-06 03:55:14,1,very poor customer service there should be a z...,"[very, poor, customer, service, there, should,..."
2,2020-05-02 01:58:12,1,app is great but service is not i really loved...,"[app, is, great, but, service, is, not, i, rea..."
3,2020-04-09 01:32:02,1,make your app trustworthy really comeon this i...,"[make, your, app, trustworthy, really, comeon,..."
4,2020-12-01 07:59:56,1,the new update ok so let us be honest i love m...,"[the, new, update, ok, so, let, us, be, honest..."
...,...,...,...,...
2564,2016-11-15 05:07:55,1,verification code time waster your verificati...,"[verification, code, time, waster, your, verif..."
2565,2015-11-29 18:38:50,4,nice one very nice idea we can buy now online ...,"[nice, one, very, nice, idea, we, can, buy, no..."
2566,2016-04-09 15:51:13,2,update please error occured when I am trying t...,"[update, please, error, occured, when, I, am, ..."
2567,2016-03-16 10:26:02,1,am i doing something wrong i can not receive t...,"[am, i, doing, something, wrong, i, can, not, ..."
2568,2015-11-07 08:17:18,1,can not open app is not working after the late...,"[can, not, open, app, is, not, working, after,..."

In [15]:
gcash_reviews_ps

,date,rating,title_review,title_review_tokenized
0,2021-06-02 18:32:37,1,good for mobile online deals,"[good, for, mobile, online, deals]"
1,2021-06-02 18:32:14,1,ilang beses nang naulit na nag load ako nag ba...,"[ilang, beses, nang, naulit, na, nag, load, ak..."
2,2021-06-02 18:32:07,4,its a great experience and convenient,"[its, a, great, experience, and, convenient]"
3,2021-06-02 18:31:31,5,ok na ok sya para sa mga easy transaction lalo...,"[ok, na, ok, sya, para, sa, mga, easy, transac..."
4,2021-06-02 18:31:25,5,very helpful and contented,"[very, helpful, and, contented]"
...,...,...,...,...
176511,2019-04-03 09:46:14,5,i love it,"[i, love, it]"
176512,2019-04-03 09:38:52,4,i love the save money and invest feature of th...,"[i, love, the, save, money, and, invest, featu..."
176513,2019-04-03 09:38:16,1,amex does not work and support is basically br...,"[amex, does, not, work, and, support, is, basi..."
176514,2019-04-03 09:33:42,5,satisfied,[satisfied]
176515,2019-04-03,1,why you keep in pop up in my phone i font like...,"[why, you, keep, in, pop, up, in, my, phone, i..."

In [16]:
paymaya_reviews_ps

,date,rating,title_review,title_review_tokenized
0,2021-06-15T10:22:11.000Z,5,i rated 1 star yesterday and if there is lower...,"[i, rated, 1, star, yesterday, and, if, there,..."
1,2021-06-15T10:08:54.000Z,2,i can not do anything with my money it always ...,"[i, can, not, do, anything, with, my, money, i..."
2,2021-06-15T10:08:14.000Z,5,masyado na kaming maraming papel dito sa bahay...,"[masyado, na, kaming, maraming, papel, dito, s..."
3,2021-06-15T10:04:31.000Z,4,upgrading account and changing no is disappoin...,"[upgrading, account, and, changing, no, is, di..."
4,2021-06-15T09:56:32.000Z,5,I am super stressed with my past ewallet app s...,"[I, am, super, stressed, with, my, past, ewall..."
...,...,...,...,...
104558,2021-06-12T06:18:19.000Z,5,very good in service easy to send get cash,"[very, good, in, service, easy, to, send, get,..."
104559,2021-06-12T06:08:23.000Z,4,bakit walang alloutsurf sa load,"[bakit, walang, alloutsurf, sa, load]"
104560,2021-06-12T04:54:57.000Z,1,keep contacting the support about the duplicat...,"[keep, contacting, the, support, about, the, d..."
104561,2021-06-12T04:03:56.000Z,5,i like this apps promise,"[i, like, this, apps, promise]"
104562,2021-06-12T02:55:36.000Z,5,nice,[nice]

##### B. Removing stop words and performing lemmenting
---
Tagalog stopwords list from: https://github.com/stopwords-iso/stopwords-tl/blob/master/stopwords-tl.json

In [17]:
with open('../../Data/Stopwords/stopwords-custom.json') as file:
    custom_stopwords = json.load(file)

In [18]:
with open('../../Data/Stopwords/stopwords-tl.json') as file:
    tl_stopwords = json.load(file)

Since nltk does not contain Tagalog stopwords, we append the Tagalog stopwords to the built-in English stopwords to create a custom taglish_stopwords list

In [20]:
taglish_stopwords = stopwords.words('english')
taglish_stopwords.extend(tl_stopwords)
taglish_stopwords.extend(custom_stopwords)
taglish_stopwords

['i',
 'me',
 'my',
 'myself',
 'we',
 'our',
 'ours',
 'ourselves',
 'you',
 "you're",
 "you've",
 "you'll",
 "you'd",
 'your',
 'yours',
 'yourself',
 'yourselves',
 'he',
 'him',
 'his',
 'himself',
 'she',
 "she's",
 'her',
 'hers',
 'herself',
 'it',
 "it's",
 'its',
 'itself',
 'they',
 'them',
 'their',
 'theirs',
 'themselves',
 'what',
 'which',
 'who',
 'whom',
 'this',
 'that',
 "that'll",
 'these',
 'those',
 'am',
 'is',
 'are',
 'was',
 'were',
 'be',
 'been',
 'being',
 'have',
 'has',
 'had',
 'having',
 'do',
 'does',
 'did',
 'doing',
 'a',
 'an',
 'the',
 'and',
 'but',
 'if',
 'or',
 'because',
 'as',
 'until',
 'while',
 'of',
 'at',
 'by',
 'for',
 'with',
 'about',
 'against',
 'between',
 'into',
 'through',
 'during',
 'before',
 'after',
 'above',
 'below',
 'to',
 'from',
 'up',
 'down',
 'in',
 'out',
 'on',
 'off',
 'over',
 'under',
 'again',
 'further',
 'then',
 'once',
 'here',
 'there',
 'when',
 'where',
 'why',
 'how',
 'all',
 'any',
 'both',
 'each',
 'few',
 'more',
 'most',
 'other',
 'some',
 'such',
 'no',
 'nor',
 'not',
 'only',
 'own',
 'same',
 'so',
 'than',
 'too',
 'very',
 's',
 't',
 'can',
 'will',
 'just',
 'don',
 "don't",
 'should',
 "should've",
 'now',
 'd',
 'll',
 'm',
 'o',
 're',
 've',
 'y',
 'ain',
 'aren',
 "aren't",
 'couldn',
 "couldn't",
 'didn',
 "didn't",
 'doesn',
 "doesn't",
 'hadn',
 "hadn't",
 'hasn',
 "hasn't",
 'haven',
 "haven't",
 'isn',
 "isn't",
 'ma',
 'mightn',
 "mightn't",
 'mustn',
 "mustn't",
 'needn',
 "needn't",
 'shan',
 "shan't",
 'shouldn',
 "shouldn't",
 'wasn',
 "wasn't",
 'weren',
 "weren't",
 'won',
 "won't",
 'wouldn',
 "wouldn't",
 'akin',
 'aking',
 'ako',
 'alin',
 'am',
 'amin',
 'aming',
 'ang',
 'ano',
 'anumang',
 'apat',
 'at',
 'atin',
 'ating',
 'ay',
 'bababa',
 'bago',
 'bakit',
 'bawat',
 'bilang',
 'dahil',
 'dalawa',
 'dapat',
 'din',
 'dito',
 'doon',
 'gagawin',
 'gayunman',
 'ginagawa',
 'ginawa',
 'ginawang',
 'gumawa',
 'gusto',
 'habang',
 'hanggang',
 'hindi',
 'huwag',
 'iba',
 'ibaba',
 'ibabaw',
 'ibig',
 'ikaw',
 'ilagay',
 'ilalim',
 'ilan',
 'inyong',
 'isa',
 'isang',
 'itaas',
 'ito',
 'iyo',
 'iyon',
 'iyong',
 'ka',
 'kahit',
 'kailangan',
 'kailanman',
 'kami',
 'kanila',
 'kanilang',
 'kanino',
 'kanya',
 'kanyang',
 'kapag',
 'kapwa',
 'karamihan',
 'katiyakan',
 'katulad',
 'kaya',
 'kaysa',
 'ko',
 'kong',
 'kulang',
 'kumuha',
 'kung',
 'laban',
 'lahat',
 'lamang',
 'likod',
 'lima',
 'maaari',
 'maaaring',
 'maging',
 'mahusay',
 'makita',
 'marami',
 'marapat',
 'masyado',
 'may',
 'mayroon',
 'mga',
 'minsan',
 'mismo',
 'mula',
 'muli',
 'na',
 'nabanggit',
 'naging',
 'nagkaroon',
 'nais',
 'nakita',
 'namin',
 'napaka',
 'narito',
 'nasaan',
 'ng',
 'ngayon',
 'ni',
 'nila',
 'nilang',
 'nito',
 'niya',
 'niyang',
 'noon',
 'o',
 'pa',
 'paano',
 'pababa',
 'paggawa',
 'pagitan',
 'pagkakaroon',
 'pagkatapos',
 'palabas',
 'pamamagitan',
 'panahon',
 'pangalawa',
 'para',
 'paraan',
 'pareho',
 'pataas',
 'pero',
 'pumunta',
 'pumupunta',
 'sa',
 'saan',
 'sabi',
 'sabihin',
 'sarili',
 'sila',
 'sino',
 'siya',
 'tatlo',
 'tayo',
 'tulad',
 'tungkol',
 'una',
 'walang',
 'gcash',
 'app',
 'po',
 'talaga',
 'nyo',
 'yung',
 'naman',
 'di',
 'paymaya',
 'lang',
 'thank',
 'please',
 'kasi',
 'mag',
 'nag']

In [21]:
def preprocess_b(corpus, column):
    tag_map = defaultdict(lambda : wn.NOUN)
    tag_map['J'] = wn.ADJ
    tag_map['V'] = wn.VERB
    tag_map['R'] = wn.ADV
    for index,entry in enumerate(corpus[column]):
        # Declaring Empty List to store the words that follow the rules for this step
        Final_words = []
        # Initializing WordNetLemmatizer()
        word_Lemmatized = WordNetLemmatizer()
        # pos_tag function below will provide the 'tag' i.e if the word is Noun(N) or Verb(V) or something else.
        for word, tag in pos_tag(entry):
            # Below condition is to check for Stop words and consider only alphabets
            if word not in taglish_stopwords and word.isalpha():
                word_Final = word_Lemmatized.lemmatize(word,tag_map[tag[0]])
                Final_words.append(word_Final)
        # The final processed set of words for each iteration will be stored in 'title_review_tokenized'
        corpus.loc[index, column] = str(Final_words)

In [22]:
preprocess_b(gcash_reviews_as,'title_review_tokenized')
preprocess_b(paymaya_reviews_as,'title_review_tokenized')

In [23]:
preprocess_b(gcash_reviews_ps,'title_review_tokenized')
preprocess_b(paymaya_reviews_ps,'title_review_tokenized')

In [24]:
gcash_reviews_as

,date,rating,title_review,title_review_tokenized
0,2018-12-29 15:24:59,3,it is starting to become pretty annoying almos...,"['start', 'become', 'pretty', 'annoy', 'almost..."
1,2020-05-16 07:33:32,5,actually ok this app gets so many negative rev...,"['actually', 'ok', 'get', 'many', 'negative', ..."
2,2020-02-04 00:25:57,3,cash in concern a little bit disappointed when...,"['cash', 'concern', 'little', 'bit', 'disappoi..."
3,2019-12-10 09:43:52,1,frustrating and slow and you are a bunch of th...,"['frustrating', 'slow', 'bunch', 'thief', 'I',..."
4,2018-06-26 18:43:31,1,payments do not post my payment via gcash did ...,"['payment', 'post', 'payment', 'via', 'post', ..."
...,...,...,...,...
4862,2016-01-16 11:52:50,1,fix this this is one of the crucial apps for g...,"['fix', 'one', 'crucial', 'apps', 'globe', 'us..."
4863,2015-11-09 08:20:37,1,can not access because they can not process my...,"['access', 'process', 'transaction', 'use', 'w..."
4864,2015-09-19 14:58:01,1,waste of time downloading compatibility says c...,"['waste', 'time', 'download', 'compatibility',..."
4865,2015-09-09 11:45:00,1,can not log in useless appcan not access my gc...,"['log', 'useless', 'appcan', 'access', 'wallet..."
4866,2015-02-06 16:10:18,2,2887 text why does it always ask me to send a ...,"['text', 'always', 'ask', 'send', 'sort', 'cod..."

In [25]:
paymaya_reviews_as

,date,rating,title_review,title_review_tokenized
0,2020-03-30 01:10:54,5,very bad service i have been contacting them a...,"['bad', 'service', 'contact', 'payment', 'make..."
1,2020-08-06 03:55:14,1,very poor customer service there should be a z...,"['poor', 'customer', 'service', 'zero', 'ratin..."
2,2020-05-02 01:58:12,1,app is great but service is not i really loved...,"['great', 'service', 'really', 'love', 'conven..."
3,2020-04-09 01:32:02,1,make your app trustworthy really comeon this i...,"['make', 'trustworthy', 'really', 'comeon', 'r..."
4,2020-12-01 07:59:56,1,the new update ok so let us be honest i love m...,"['new', 'update', 'ok', 'let', 'u', 'honest', ..."
...,...,...,...,...
2564,2016-11-15 05:07:55,1,verification code time waster your verificati...,"['verification', 'code', 'time', 'waster', 've..."
2565,2015-11-29 18:38:50,4,nice one very nice idea we can buy now online ...,"['nice', 'one', 'nice', 'idea', 'buy', 'online..."
2566,2016-04-09 15:51:13,2,update please error occured when I am trying t...,"['update', 'error', 'occur', 'I', 'try', 'log'..."
2567,2016-03-16 10:26:02,1,am i doing something wrong i can not receive t...,"['something', 'wrong', 'receive', 'verificatio..."
2568,2015-11-07 08:17:18,1,can not open app is not working after the late...,"['open', 'work', 'late', 'update', 'wtf']"

In [26]:
gcash_reviews_ps

,date,rating,title_review,title_review_tokenized
0,2021-06-02 18:32:37,1,good for mobile online deals,"['good', 'mobile', 'online', 'deal']"
1,2021-06-02 18:32:14,1,ilang beses nang naulit na nag load ako nag ba...,"['ilang', 'be', 'nang', 'naulit', 'load', 'baw..."
2,2021-06-02 18:32:07,4,its a great experience and convenient,"['great', 'experience', 'convenient']"
3,2021-06-02 18:31:31,5,ok na ok sya para sa mga easy transaction lalo...,"['ok', 'ok', 'sya', 'easy', 'transaction', 'la..."
4,2021-06-02 18:31:25,5,very helpful and contented,"['helpful', 'content']"
...,...,...,...,...
176511,2019-04-03 09:46:14,5,i love it,['love']
176512,2019-04-03 09:38:52,4,i love the save money and invest feature of th...,"['love', 'save', 'money', 'invest', 'feature']"
176513,2019-04-03 09:38:16,1,amex does not work and support is basically br...,"['amex', 'work', 'support', 'basically', 'brai..."
176514,2019-04-03 09:33:42,5,satisfied,['satisfied']
176515,2019-04-03,1,why you keep in pop up in my phone i font like...,"['keep', 'pop', 'phone', 'font', 'like', 'add']"

In [27]:
paymaya_reviews_ps

,date,rating,title_review,title_review_tokenized
0,2021-06-15T10:22:11.000Z,5,i rated 1 star yesterday and if there is lower...,"['rat', 'star', 'yesterday', 'low', 'star', 'w..."
1,2021-06-15T10:08:54.000Z,2,i can not do anything with my money it always ...,"['anything', 'money', 'always', 'say', 'shop',..."
2,2021-06-15T10:08:14.000Z,5,masyado na kaming maraming papel dito sa bahay...,"['kaming', 'maraming', 'papel', 'bahay', 'need..."
3,2021-06-15T10:04:31.000Z,4,upgrading account and changing no is disappoin...,"['upgrade', 'account', 'change', 'disappoint',..."
4,2021-06-15T09:56:32.000Z,5,I am super stressed with my past ewallet app s...,"['I', 'super', 'stress', 'past', 'ewallet', 's..."
...,...,...,...,...
104558,2021-06-12T06:18:19.000Z,5,very good in service easy to send get cash,"['good', 'service', 'easy', 'send', 'get', 'ca..."
104559,2021-06-12T06:08:23.000Z,4,bakit walang alloutsurf sa load,"['alloutsurf', 'load']"
104560,2021-06-12T04:54:57.000Z,1,keep contacting the support about the duplicat...,"['keep', 'contact', 'support', 'duplicate', 'a..."
104561,2021-06-12T04:03:56.000Z,5,i like this apps promise,"['like', 'apps', 'promise']"
104562,2021-06-12T02:55:36.000Z,5,nice,['nice']

##### C. Filtering by date and ratings
---

In [28]:
start_date = "2020-01-01"
end_date = "2021-05-31"

In [32]:
def preprocess_c(corpus):
    corpus['date'] = pd.to_datetime(corpus['date'])
    corpus = corpus.loc[(corpus['date'] >= start_date) & (corpus['date'] <= end_date)]
    corpus = corpus.sort_values(by='date')
    corpus_good = corpus.loc[corpus['rating'] >= 4]
    corpus_bad = corpus.loc[corpus['rating'] <= 3]
    return corpus_good, corpus_bad

In [30]:
gcash_good_as, gcash_bad_as = preprocess_c(gcash_reviews_as)
paymaya_good_as, paymaya_bad_as = preprocess_c(paymaya_reviews_as)

In [36]:
gcash_good_ps, gcash_bad_ps = preprocess_c(gcash_reviews_ps)
paymaya_good_ps, paymaya_bad_ps = preprocess_c(paymaya_reviews_ps)

In [37]:
gcash_good_as

,date,rating,title_review,title_review_tokenized
812,2020-01-10 03:29:09,5,nice so far so good convenient no problem enco...,"['nice', 'far', 'good', 'convenient', 'problem..."
3234,2020-01-17 17:59:30,5,good service plz support gcash,"['good', 'service', 'plz', 'support']"
56,2020-01-20 17:32:16,4,incoming outgoing transaction limits hello gc...,"['incoming', 'outgo', 'transaction', 'limit', ..."
489,2020-01-23 00:33:47,5,convenience since the day i installed the apps...,"['convenience', 'since', 'day', 'instal', 'app..."
792,2020-01-25 06:41:20,4,icons the app is ok but maybe stop rearranging...,"['icon', 'ok', 'maybe', 'stop', 'rearrange', '..."
...,...,...,...,...
2703,2021-05-25 02:44:16,4,customer service medyo makulit ako at maraming...,"['customer', 'service', 'medyo', 'makulit', 'm..."
2371,2021-05-26 13:37:55,5,face id pls bring back the face id security fe...,"['face', 'id', 'pls', 'bring', 'back', 'face',..."
186,2021-05-27 14:59:34,4,slightly not safe may i know what are the othe...,"['slightly', 'safe', 'know', 'way', 'access', ..."
619,2021-05-29 04:13:21,5,g cash allow nickname i hope next update of gc...,"['g', 'cash', 'allow', 'nickname', 'hope', 'ne..."
1056,2021-05-30 13:30:42,4,payment problems gcash keeps blocking my payme...,"['payment', 'problem', 'keep', 'block', 'payme..."

In [38]:
gcash_bad_as

,date,rating,title_review,title_review_tokenized
161,2020-01-01 02:10:56,3,needs improvement gcash is a great app but if ...,"['need', 'improvement', 'great', 'try', 'buy',..."
4655,2020-01-01 11:26:33,1,gcash is a total scam andami ng videos sa yout...,"['total', 'scam', 'andami', 'video', 'youtube'..."
793,2020-01-01 15:11:30,3,email registration error i cannot log in my e...,"['email', 'registration', 'error', 'log', 'ema..."
69,2020-01-01 19:14:19,1,customer support during issues is trash been a...,"['customer', 'support', 'issue', 'trash', 'avi..."
3631,2020-01-02 01:43:34,1,2020 outdate please keep up with 2020 it is wo...,"['outdate', 'keep', 'bad', 'dial']"
...,...,...,...,...
3588,2021-05-28 13:04:29,1,scammer is always scammer and tha is globe tel...,"['scammer', 'always', 'scammer', 'tha', 'globe..."
1823,2021-05-29 22:31:59,3,do not reset the dashboard every update i had ...,"['reset', 'dashboard', 'every', 'update', 'rea..."
3852,2021-05-30 06:38:52,1,worst app ever worst app an customer service,"['bad', 'ever', 'worst', 'customer', 'service']"
1272,2021-05-30 08:39:15,2,gcredit application page is buggy i was not ab...,"['gcredit', 'application', 'page', 'buggy', 'a..."
339,2021-05-30 15:06:51,1,great but worse the app itself is amazing it ...,"['great', 'worse', 'amaze', 'glitchy', 'proble..."

In [39]:
paymaya_good_ps

,date,rating,title_review,title_review_tokenized
61220,2020-01-01 00:47:06+00:00,5,good,['good']
61219,2020-01-01 01:38:31+00:00,5,very convenient,['convenient']
61218,2020-01-01 01:38:48+00:00,5,great app and service,"['great', 'service']"
61217,2020-01-01 02:50:56+00:00,5,satisfaction guaranteed,"['satisfaction', 'guarantee']"
61215,2020-01-01 03:13:09+00:00,5,this is so usefull and i loved the cashback,"['usefull', 'love', 'cashback']"
...,...,...,...,...
2703,2021-05-30 23:07:43+00:00,5,maganda ang paymaya,['maganda']
2702,2021-05-30 23:28:53+00:00,5,verynice,['verynice']
2701,2021-05-30 23:31:00+00:00,5,nice,['nice']
2700,2021-05-30 23:42:56+00:00,5,mas favor ko ang actual card ng application da...,"['ma', 'favor', 'actual', 'card', 'application..."
2699,2021-05-30 23:55:17+00:00,5,I am playing all ready,"['I', 'play', 'ready']"

In [41]:
paymaya_bad_ps

,date,rating,title_review,title_review_tokenized
61216,2020-01-01 03:09:08+00:00,1,fix your connection issues and account upgrade...,"['fix', 'connection', 'issue', 'account', 'upg..."
61214,2020-01-01 03:16:20+00:00,2,too bad,['bad']
61212,2020-01-01 04:08:40+00:00,1,their services sucks,"['service', 'suck']"
61210,2020-01-01 06:24:52+00:00,1,if there is a zero star I will rate it as zero...,"['zero', 'star', 'I', 'rate', 'zero', 'stupid'..."
61205,2020-01-01 08:35:19+00:00,1,stupod appthe upgrade is stupid i get record m...,"['stupod', 'appthe', 'upgrade', 'stupid', 'get..."
...,...,...,...,...
2722,2021-05-30 20:22:26+00:00,1,can not student id,"['student', 'id']"
2720,2021-05-30 20:45:45+00:00,1,maganda sana kaso napakatagal mag email back s...,"['maganda', 'sana', 'kaso', 'napakatagal', 'em..."
2716,2021-05-30 21:12:16+00:00,1,useless csr,"['useless', 'csr']"
2708,2021-05-30 22:37:40+00:00,1,can not download the app,['download']
2704,2021-05-30 22:54:59+00:00,1,it is so hard to upgrade my account just so i ...,"['hard', 'upgrade', 'account', 'get', 'money',..."

##### D. Saving the files
---

In [44]:
gcash_good_as.to_csv('../../Data/Preprocessed/Mico/P1/gcash_good_as.csv', index=False)
gcash_bad_as.to_csv('../../Data/Preprocessed/Mico/P1/gcash_bad_as.csv', index=False)
paymaya_good_as.to_csv('../../Data/Preprocessed/Mico/P1/paymaya_good_as.csv', index=False)
paymaya_bad_as.to_csv('../../Data/Preprocessed/Mico/P1/paymaya_bad_as.csv', index=False)

In [45]:
gcash_good_ps.to_csv('../../Data/Preprocessed/Mico/P1/gcash_good_ps.csv', index=False)
gcash_bad_ps.to_csv('../../Data/Preprocessed/Mico/P1/gcash_bad_ps.csv', index=False)
paymaya_good_ps.to_csv('../../Data/Preprocessed/Mico/P1/paymaya_good_ps.csv', index=False)
paymaya_bad_ps.to_csv('../../Data/Preprocessed/Mico/P1/paymaya_bad_ps.csv', index=False)